### ISSUE TITLE
Set default terminal theme after installing

### ISSUE THREAD

**Issue by jennykortina** [kortina/dotfiles#6]
![screen shot 2017-05-08 at 11 16 43 pm](https://cloud.githubusercontent.com/assets/367902/25881465/0f5ea06e-350b-11e7-8634-45fdf92bfe9f.png)

**Comment by kortina** [comment]
Some recent commits such as https://github.com/kortina/dotfiles/commit/8f39213b58d19771052c7e9e1891f4b8189bc31d#diff-b71e339b7ec5fad91dda1b803a2ee54cR63 fix this
